# Generated for local dev only.
# In production, replace operator.jwt path and resolver dir.

server_name: "nats-admin-dev"
listen: "0.0.0.0:4222"
http: "0.0.0.0:8222"
operator: "/workspace/nats-admin/nats/operator.jwt"
resolver: {
  type:         full
  dir:          "/data/nats/resolver"
  allow_delete: true
  interval:     "2m"
}
system_account: "ADJCNTHGCBFV4PKCRGECBRO6TPREFET7E2QR2LSW6X465U4F6V7OCKCW"

leafnodes: {
  listen: "0.0.0.0:7422"
}

jetstream {
  store_dir: "/data/nats/jetstream"
  max_memory_store: 1G
  max_file_store: 10G
}

debug: false
trace:  false
